### ISSUE TITLE
Blaze.TemplateInstance as this

### ISSUE THREAD

**Issue by abuszta** [chriswessels/meteor-hammer#10]
Any good reason why Blaze.TemplateInstance is passed as this to gesture callback instead of data context? This prevents from doing similar or even same handling for events and gestures...

Eg. I can create such click event:

    Template.page.events({
        'click button': function(event, template) {
            console.log(event); // accessing event
            console.log(template); // accessing template
            console.log(this); // accessing current data context
        }
    });

However for example press gesture:

    Template.page.gestures({
        'press button': function(event) {
            console.log(event); // accessing event
            console.log(this); // accessing template
            //console.log(...); // how to access data context?
        }
    });

Is it hard to implement? Or maybe I'm missing something? How to access data context from gesture?

Here is some more information about data context: http://stackoverflow.com/a/15149650

**Comment by chriswessels** [comment]
Hey @abuszta,

Good catch. I've just released version 3.0.0-rc2 which implements the behaviour you've recommended.

```
Template.yourTemplate.gestures({
  'swipeleft .item .panel': function (event, template) {
    /* Do something when user swipes left on .item .panel (elements(s) inside the template html) */
    /* `event` is the Hammer.js event object */
    /* `template` is the `Blaze.TemplateInstance` */
    /* `this` is the data context of the element in your template */
  }
});
```

Please let me know if this works for you.

Kind regards,
Chris

**Comment by yubozhao** [comment]
@chriswessels 

Awesome package!  But the new 3.0.0 hasn't been published into atmosphere yet   :(

**Comment by chriswessels** [comment]
Hey @yubozhao 

It has, but because it's not a stable release it's not displayed.

If you the following command in your Meteor project folder

    meteor add chriswessels:hammer@3.0.0-rc2

You will get the release candidate containing the latest changes.

Please let me know if this works for you. I'm keen to release 3.0.0 as stable for general use.

Kind regards,
Chris

**Comment by abuszta** [comment]
Hey @chriswessels,

I added new version to my project and I see two issues here:

* 'this' returns always first element of the collection (I have few buttons and every button has press gesture set up using 'press button.class' to execute console.log(this), and it seems that they are always returning same object)
* with version 3+ I think gestures stopped propagating or are working worse now. I have swipeleft and swiperight gestures set up for div element, and this gestures are now propagating only when swipe is done exactly over this element (it is not working when there are some buttons over this div). I don't know if this is issue with my application, but I think it was working before, so I'm just curious if something connected to that was changed :)

**Comment by chriswessels** [comment]
Thanks for the bug reports @abuszta! I'll sort these out tomorrow morning and let you know.

**Comment by chriswessels** [comment]
Hey @abuszta 

I've just pushed 3.0.0-rc3 which addresses both of the issues you've identified above.

Please `meteor add chriswessels:hammer@3.0.0-rc3` and let me know if all is working as expected.

Thanks!
Chris

**Comment by abuszta** [comment]
Thanks @chriswessels! It's seems to be working right now :)

**Comment by yubozhao** [comment]
@chriswessels Great. thanks for the cool trick on update

**Comment by chriswessels** [comment]
Good to hear @abuszta, thanks for the reports!

No problem @yubozhao, I'm going to release 3.0.0 stable now so it should become visible on Atmosphere.
