### ISSUE TITLE
Why is Hammer applied to body on startup?

### ISSUE THREAD

**Issue by dalgard** [chriswessels/meteor-hammer#13]
From `template_integration.js`:

```javascript
Meteor.startup(function () {
  $('body').hammer({});
  Template.onRendered(setupTemplateGestures);
  Template.onDestroyed(teardownTemplateGestures);
});
```

The CSS properties are applied to `body` before I can delete them in my code. Very annoying.

All in all, template integration seems like a lot of overhead for a simple library...

**Comment by chriswessels** [comment]
Hi @dalgard,

Feel free to use https://atmospherejs.com/hammer/hammer for bundling Hammer.js if you don't want any other features. Or submit a pull request here with suggested improvements.

Chris

**Comment by dalgard** [comment]
Sorry, I didn't mean to be rude. And you're right – although, that package doesn't work currently.

Still, why is Hammer applied to body automatically? Deleting properties on cssProps isn't having any effect when Hammer is already applied.

**Comment by chriswessels** [comment]
@dalgard, hope you're well.

Pushed an updated README for the slated 4.0.0 release: https://github.com/chriswessels/meteor-hammer/blob/rewrite/README.md

Hammer is no longer applied to `body` on startup - as a developer you can control how many instances are created and where they live. You'll see that it also allows you to specify `cssProps`.

You can test this functionality with $ meteor add chriswessels:hammer@4.0.0-rc1.

Chris

**Comment by dalgard** [comment]
Hey – thanks :) Funny coincidence, I am reading up on Hammer for the first time in months right this moment. I'm trying to find out whether I could make my side menu draggable (snapping into place) with a reasonable amount of work.
