### ISSUE TITLE
Destroy hammer instance onDestroyed

### ISSUE THREAD

**Issue by rclai** [chriswessels/meteor-hammer#16]
Shouldn't you implement `onDestroyed` to clean up the Hammer instance?

```js
Template.HammerTouchArea.onDestroyed(function () {
  this._hammer.instance && this._hammer.instance.destroy(); // or it just .off() ?
});
```

**Comment by chriswessels** [comment]
@rclai You're correct! I've pushed 4.0.1 which includes Hammer.js instance teardown.

Thanks for taking the time to submit an issue :smile:

Chris

**Comment by rclai** [comment]
No problem man.
