### ISSUE TITLE
Anyway to remove the div created by the plugin?

### ISSUE THREAD

**Issue by voidale** [chriswessels/meteor-hammer#19]
Hey,

Awesome package, Love it it's a "meteor way" package. I'm having issues because it adds extra divs and way to avoid the divs?

**Comment by chriswessels** [comment]
Hey @voidale, thanks!

What issues are the wrapper divs causing? You should get one div per `HammerTouchArea` (and you shouldn't need more than 1 per template unless you're doing something special).

It is essential to have the divs in place, as these are the elements that the Hammer.js instances are listening for touch events on.

Chris

**Comment by voidale** [comment]
@chriswessels I mean I rather just specify the element my self because I have existing ones, And it's on a big project lots of old css and scripts depend on the divs (custom scroll bar for example). It will take long time making sure it works right. And also if not wrong some of other packages like semantic-ui for meteor extra divs can cause trouble (https://github.com/meteorhacks/flow-layout/issues/10) I can't remember all the use cases. But I think it's just matter of time more problems can come from this. So if there was an easy way to just let a custom div to be used that will solve future problems :)

**Comment by chriswessels** [comment]
@voidale I see... Unfortunately the package is not architected in a way that would make that easy. It's purposeful that the instance of `HammerTouchArea` corresponds with the div that hammer is attached to (Blaze template instance lifecycle).

You could try creating an instance of Hammer yourself and attaching it to the wrapper div you already have. Use `new Hammer` in `Template.foo.onRendered` and then use `hammerInstance.destroy()` in `Template.foo.onDestroyed`.
