### ISSUE TITLE
pinch gestures - no difference between in & out

### ISSUE THREAD

**Issue by acidicX** [chriswessels/meteor-hammer#20]
Hey,
thanks for the great plugin. I'm having an issue with pinch recognizers.
I added the pinch recognizer by using the configuration callback:
````
configureHammer: function () {
  return function (hammer, templateInstance) {
    var pinch = new Hammer.Pinch();
    hammer.add(pinch);
    return hammer;
  };
},
````
According to the hammer docs, this should give me the 'pinchout' and 'pinchin' events.
If I add a 'pinchout' in my templateGestures...
````
'pinchout div': function (event, templateInstance) {
  Router.go('/myroute/');
}
````
... it does trigger - however, it also triggers on a zoom-in pinch (even though I have not specified any 'pinchin' in templateGestures).
If I add the 'pinchin', most of the time both events trigger.

I've tested the events on the same device with standard hammer, like here:
http://codepen.io/anon/pen/JdrVOr
and it works way better.
Seems to be an issue with this wrapper then?

**Comment by chriswessels** [comment]
Hey @acidicX,

I suspect this issue may be because this plugin instantiates Hammer with the default set of recognizers, including the default pinch recognizer (so it does `new Hammer()` instead of `new Hammer.Manager()`). This is so that basic use of the plugin is super easy and no additional configuration is required. Have a look at: http://hammerjs.github.io/api/#hammer

You have two options:

1. Set `initOptions` in your `HammerTouchArea` to an object containing the `recognizers` property - an array of recognizers you want enabled. This will override the default behaviour.

2. In your `configureHammer` callback, instantiate your own instance of `Hammer.Manager` and return it instead of the `hammer` instance passed into the callback function.

e.g.
```
configureHammer: function () {
  return function (hammer, templateInstance) {
    var mc = new Hammer.Manager(myElement);

    // create a pinch and rotate recognizer
    // these require 2 pointers
    var pinch = new Hammer.Pinch();
    var rotate = new Hammer.Rotate();

    // we want to detect both the same time
    pinch.recognizeWith(rotate);

    // add to the Manager
    mc.add([pinch, rotate]);

    return mc;
  };
},
```

Please let me know how this works for you and I'll update the README to make this clearer.

Kind regards,
Chris

**Comment by acidicX** [comment]
Thanks for the fast reply @chriswessels 
I tried before with the initOptions to set recognizers, but I didn't get the syntax worked out. This is missing in the README as well ;-) how does the array look like to enable pinch? The section in the hammer API uses a callback for recognizers..

For 2.: what do I need to pass to Hammer.Manager? (myElement ...)
This should be the 'hammer-touch-area' in my template, right? But how do I get that?

Cheers,
Carsten

**Comment by chriswessels** [comment]
No problem @acidicX. I would do it using `initOptions` to disable the default recognizers, and then do setup as you wish in `configureCallback`.

#### Example:

```html
<template name="bar">
  {{#HammerTouchArea initOptions=hammerInitOptions gestureMap=templateGestures configureCallback=configureHammer}}
    <!-- Your HTML that is matched against `templateGestures` -->
  {{/HammerTouchArea}}
</template>
```

```javascript
Template.bar.helpers({
  hammerInitOptions: {
    recognizers: []
  },
  configureHammer: function () {
    return function (hammer, templateInstance) {
      var pinch = new Hammer.Pinch();
      var rotate = new Hammer.Rotate();

      // we want to detect both the same time
      pinch.recognizeWith(rotate);

      // add to the Manager
      hammer.add([pinch, rotate]);
      return hammer;
    };
  },
  templateGestures: {
    /* Object mapping selectors to gesture callbacks, see above for example */
  }
});
```

Please let me know if this helps!

Chris

**Comment by acidicX** [comment]
Alright, I tried that now, but it still won't work properly. Sometimes both events fire, sometimes only one (sometimes the right one, sometimes the wrong)... :-(

**Comment by acidicX** [comment]
I think I found the problem :-)
I had two overlapping HammerTouchAreas (first one in the main template, second in a yield nested inside the main template). The second one was only used for tap & press and had no pinch recognizers, so no events should have bubbled up. Still, after I merged all templateGestures in the upper hammer area (main template) the issue vanished.

It is still weird, it seems that blocked events bubbled up and also the wrong ones were triggered (pinch-in instead of out, and vice-versa). But at least it works now.
Having nested templates with HammerTouchAreas seems to be no good idea!

**Comment by chriswessels** [comment]
@acidicX I'm glad you figured it out :)

That's pretty strange behaviour, but it does make sense. Instances of HammerTouchArea correspond with instances of `Hammer.Manager`, and unless you explicitly disable them, the default setup will include all of the basic recognizers. Perhaps this should change...

Chris
