### ISSUE TITLE
swipeleft / swiperight not working

### ISSUE THREAD

**Issue by ClaudeBotes** [chriswessels/meteor-hammer#21]
Hi,

This seems like a great lib, but I can't seem to get it working for swipeleft/swiperight events. I can get it working for 'press' and 'tap', but not any of the swipes... anyone experiencing the same issue or have a solution?

I tried a custom hammer configuration, but that did not work either...

//what works
//html
{{#HammerTouchArea gestureMap=fooGestures}}
            <div class="bar" style="background-color: #0000cc; height: 40px; width: 40px;">
                <small>Test</small>
            </div>
{{/HammerTouchArea}}

//JS
fooGestures: {
            'tap .bar': function (event, template) {
                console.log('do something');
            }
  }

//JS - does not work
fooGestures: {
            'swipeleft .bar': function (event, template) {
                console.log('do something');
            }
  }

//same goes for swiperight and swipe

Thanks in advance for any help

**Comment by chriswessels** [comment]
Hi @ClaudeBotes,

How are you testing the swipe events? Some events like press and tab will be registered in the browser as standard, but others will only be registered on a mobile device, or a browser that is configured to emulate touch events.

Take a look here: https://developer.chrome.com/devtools/docs/device-mode

It explains how to enable mobile device emulation in Chrome, including touch event emulation.

Kind regards,
Chris

**Comment by ClaudeBotes** [comment]
Hi @chriswessels ,

Thanks for the feedback...I don't think I would have ever came to that solution...thought perhaps something was wrong in my code.

Quickly switching to mobile mode it looks like the swipe events are triggering as expected. Though it only triggers on the first swipe and not any after the first swipe... will do a few more tests on this...at least I know the event is triggering and I can debug from here.

Thanks a mil

**Comment by chriswessels** [comment]
@ClaudeBotes glad to hear it. Let me know if you have any more issues.

Chris
