### ISSUE TITLE
'threshold' not recognized in pan events

### ISSUE THREAD

**Issue by salilsethi** [chriswessels/meteor-hammer#22]
I am setting threshold in the hammerInitOptions but the panleft and panright in the gestureMap do not seem to react to the change in threshold value.

Any help would be appreciated.

**Comment by chriswessels** [comment]
Hey @salilsethi,

`hammerInitOptions` is useful for setting pre-initialisation options, but when doing more advanced configuration, I use the `configureCallback` property to programatically configure Hammer.js.

Example:

```
Template.baz.helpers({
  configureHammer: function () {
    return function (hammer, templateInstance) {
      hammer.get('pan').set({ threshold: 5 });
      return hammer;
    }
  },
  /* ... */
});
```

Make sure to return the hammer instance once you are done configuring it.

Hope this helps.

Chris

**Comment by salilsethi** [comment]
@chriswessels Thanks for the message. closing the issue.
