### ISSUE TITLE
No such template: HammerTouchArea

### ISSUE THREAD

**Issue by JulianKingman** [chriswessels/meteor-hammer#24]
Any idea why I'm getting this error?

```
Exception in defer callback: Error: No such template: HammerTouchArea
```

There relevant code:

``` javascript
{{#HammerTouchArea gestureMap=touchEvents}}
          <ul>
            {{#each obj}}
                <li>{{example}}</li>
            {{/each}}
          </ul>
{{/HammerTouchArea}}
```

And the obvious: chriswessels:meteor-hammer is installed

**Comment by chriswessels** [comment]
Please could you provide the output of `meteor list`.

**Comment by JulianKingman** [comment]
So, I’m using this inside of a package. Meteor list outputs this: 

chriswessels:hammer           2.0.4_3\* Bundles Hammer.js and provides Template.templateName.gestures() for easy use of multitouch gestures.
coffeescript                  1.0.11  Javascript dialect with fewer braces and semicolons
fastclick                     1.0.7  Faster touch events on mobile
raix:push                     0.0.1\* Meteor push server for IOS and android
reywood:publish-composite     1.4.2  Publish a set of related documents from multiple collections with a reactive join
telescope-theme-snowball      0.0.1+ Telescope snowball theme
telescope:api                 0.25.6+ Telescope API package
telescope:core                0.25.6+ Telescope core package
telescope:daily               0.25.6+ Telescope daily view
telescope:datetimepicker      0.25.6+ Custom bootstrap-datetimepicker input type for AutoForm
telescope:debug               0.25.6+ Telescope debug package
telescope:email               0.25.6+ Telescope email package
telescope:embedly             0.25.6+ Telescope Embedly module package
telescope:getting-started     0.25.6+ Getting started posts
telescope:invites             0.25.6+ Telescope invites package
telescope:kadira              0.25.6+ Telescope Kadira package
telescope:migrations          0.25.6+ Telescope migrations package
telescope:newsletter          0.25.7+ Telescope email newsletter package
telescope:notifications       0.25.6+ Telescope notifications package
telescope:pages               0.25.6+ Telescope static pages package
telescope:post-by-feed        0.25.6+ Auto post via RSS to Telescope
telescope:prerender           0.25.6+ Telescope Prereder.io package
telescope:releases            0.25.6+ Show Telescope release notes and phone home with some stats.
telescope:rss                 0.25.6+ Telescope RSS package
telescope:scoring             0.25.6+ Telescope scoring package.
telescope:search              0.25.6+ Telescope search package
telescope:share               0.25.6+ Telescope share module package
telescope:spiderable          0.25.6+ Telescope Spiderable package.
telescope:subscribe-to-posts  0.25.6+ Subscribe to posts to be notified when they get new comments
telescope:tagline-banner      0.25.6+ Show a banner containing your site's tagline on the homepage
telescope:tags                0.25.6+ Telescope tags package
telescope:theme-base          0.25.6+ Telescope base theme package
telescope:theme-hubble        0.25.6+ Telescope Hubble theme package
telescope:update-prompt       0.25.6+ Telescope update prompt package.

and in the package.js, I have this:
api.use([
  'telescope:core',
  'telescope:notifications',
  'telescope:tags',
  'telescope:users',
  'matb33:collection-hooks',
  'aldeed:simple-schema',
  'aldeed:autoform',
  'comerc:autoform-selectize',
  'jeremy:selectize',
  'aldeed:autoform-select2',
  'daviator:select2',
  'easy:search',
  'raix:push',
  'kestanous:herald',
  'matb33:collection-hooks’,
  //note: I had this in client only, but moved to both after it wasn’t working
  'chriswessels:hammer'
], ['client', 'server']);

Thanks for the help!

**Comment by chriswessels** [comment]
Ah, that's the problem. The version constraint solver works slightly differently for package dependencies (frustrating inconsistency in my opinion). You need to specify a version as it doesn't use the latest version by default...

Specify the following string in your `api.use` call: `chriswessels:hammer@4.0.2`

**Comment by JulianKingman** [comment]
Awesome, thanks Chris, you also solved my problems with `raix:push`, and probably a host of other issues I've been having. In the absence of a version constraint, how does Meteor determine which version to use? And any idea why a 'swipe'  events wouldn't be registering?

**Comment by chriswessels** [comment]
@JulianKingman Happy to help. I remember there being a forum post on version selection (and the differences in selection between app dependencies and package dependencies) on forums.meteor.com.

This shouldn't matter much though as Meteor is moving away from the smart package model and will be adopting standard npm packages from 1.3 onwards.

Not sure about the swipe events, although the events themselves are `swipeleft`, `swipedown` or similar.
