### ISSUE TITLE
Getting "undefined is not a function"

### ISSUE THREAD

**Issue by adamgins** [chriswessels/meteor-hammer#3]
Hi, just installed your package.

I am trying to run a simple example:

```
var hammertime = new Hammer('body');
    hammertime.on('tap', function(e) {
        console.log(e);
    });
```

I get the following error:
```
29debug.js:41 Exception from Tracker afterFlush function: undefined is not a function
TypeError: undefined is not a function
    at http://localhost:3000/packages/chriswessels_hammer.js?e5139bcc7190a2209101a2ee682090f028e17e61:198:16
    at Array.forEach (native)
    at each (http://localhost:3000/packages/chriswessels_hammer.js?e5139bcc7190a2209101a2ee682090f028e17e61:90:13)
```
Any ideas, pls?

**Comment by chriswessels** [comment]
Hi @adamgins,

This is untested, but if I remember correctly you need to pass the DOM element instance into Hammer. If you're using jQuery, try something like this:

    var hammertime = new Hammer($('body').get(0));

Let me know if that works for you.

Chris

**Comment by adamgins** [comment]
Thanks @chriswessels 
I endued up just putting the hammer . js file and jquery into my project and it's working... that said having  some issues making it play nicely with other packages like Froala... each seem to be fighting to own the event and it's different across different browsers

**Comment by chriswessels** [comment]
No problem @adamgins!

I've just updated chriswessels:hammer to ease the actual use of Hammer.js with Meteor. Take a look at the new project README. If you were/are using an instance of Hammer.js attached to the body element, that might explain the conflicts with other packages. Try implementing via `Template.templateName.gestures()` with the new chriswessels:hammer - it might just resolve the conflict.

Chris
