### ISSUE TITLE
Simple test, not working

### ISSUE THREAD

**Issue by ashah888** [chriswessels/meteor-hammer#6]
Hello,

I tried testing out the package by doing a very simple test but no avail. Are there any pre-requisites to using this package?

Template.NAME.gestures({
	'swipeleft .img-contain': function(){
		alert("test")
	},
	'tap': function(){
		alert("test")
	},
})

**Comment by chriswessels** [comment]
@ashah888, the swipeleft event should work, however tap won't because you haven't specified an element.
