### ISSUE TITLE
hammerOptions not working on mobile?

### ISSUE THREAD

**Issue by aurnik** [chriswessels/meteor-hammer#8]
So the package works great before setting the Template.template_name.hammerOptions, but once I do that the events only register on desktop and not mobile. Here's my options layout:

```
Template.song_info.hammerOptions({
    recognizers: [
        [Hammer.Press,{ time: 500 }],
        [Hammer.Tap, {taps: 2}],
        [Hammer.Pan, {threshold: 1, direction: 6}]
    ]
});
```

**Comment by chriswessels** [comment]
Hi @aurnik, `hammerOptions` just passes the object you provide straight into Hammer.js upon instance initialisation. It doesn't change the behaviour of meteor-hammer, so I'm not sure why you're experiencing this behaviour.

How are you attaching your callbacks to the events?

**Comment by aurnik** [comment]
Ah I don't know what the problem was but it's fixed itself. The press seemed to be overlapping the other two events not allowing them to be called but it works now. Sorry about that, looks like it figured itself out!
