### ISSUE TITLE
Rerouting kills functionality

### ISSUE THREAD

**Issue by logansparlin** [chriswessels/meteor-hammer#9]
If you reroute using the same template, but filling it with different data, the hammer.js functionality no longer works. 

For example, I have a template called mobileBooks. So if I'm searching for a book in the category of "fiction" my route will be url/books/thrillers. If I then change the category to "nonfiction" and reroute to url/books/nonfiction using the same Template and a Router.go() the Hammer.js swipe functionality no longer works unless I refresh the page.

**Comment by chriswessels** [comment]
Hey @logansparlin

I had some time to look at this recently and have released 3.0.0-rc1. The package is architected slightly differently under the hood and uses a single instance of Hammer.js attached to the body element which is immune to Blaze DOM updates (which were previously causing the bug you experienced).

Hammer options are now set application-wide rather than per-template. `Template.templateName.hammerOptions(options)` has been deprecated and replaced with `$('body').data('hammer').set(options)`.

You can try the new package with
    `$ meteor add chriswessels:hammer@3.0.0-rc1`

Please let me know if it works for you.

Thanks,
Chris

**Comment by logansparlin** [comment]
Hey @chriswessels does the actual call to hammer still work the same? Is the correct syntax still as follows:

Template.templateName.gestures({
     "event element": function() {
          // do something when event happens
     }
})

Or does it need to be set application-wide somehow as well?

**Comment by logansparlin** [comment]
Hey @chriswessels 

Is the correct syntax for setting gestures still as follows? 

```javascript 
Template.templateName.gestures({
    "event element": function(ev) {
        // do on triggered event
}
})
```

Or do I need to set the event on an application level rather than template level?

**Comment by chriswessels** [comment]
Hey @logansparlin. Yes - it's the same as before. Only the Hammer options are set application-wide.

**Comment by chriswessels** [comment]
Closing this for now as I think it's fixed with the 3.0.0-rc2 version.

Will be releasing 3.0.0 stable soon for general use.

Thanks for the issue report @logansparlin.

**Comment by DenLilleMand** [comment]
Hey .. im useing  version 3.1.1 and i have the same issue. Works perfect, right up until i go to /eventdetails/xxx
and then click the navigation back to the area with the .slide-left / .slide-right classes. 
Navigation back implementation: 
Snippet:
Template.ionNavBackButton.events({
  'click': function (event, template) {
    $('[data-nav-container]').addClass('nav-view-direction-back');
    $('[data-navbar-container]').addClass('nav-bar-direction-back');

    if (template.backUrl) {
      Router.go(template.backUrl);  //we should imagine the swipe area template here. so basically
                                                  //the issue is with Router.go(swipeAreaTemplate);

    } else {
      window.history.back();
    }
  }
});

Swipe area:
<div class="swiped-right swiped-left" id="calendar"></div>  //fullcalendar implementation

back-navigation area:
{{#contentFor "headerButtonLeft"}}
        {{>ionNavBackButton path="calendar"}}
    {{/contentFor}}

**Comment by DenLilleMand** [comment]
Just bumping this.

**Comment by chriswessels** [comment]
@DenLilleMand thanks for the report.

As I'd like to fix this and have the package as ideally structured as possible, I've opened a discussion asking for guidance here: https://forums.meteor.com/t/guidance-needed-for-chriswessels-hammer-hammer-js-blaze-integration/3532

Hopefully we'll have a solution soon!

Chris
